{block content}

<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode    : "textareas",
        theme   : "advanced",
        plugins : "spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,filemanager",

        // Theme options
        theme_advanced_buttons1 : "bold,italic,underline,undo,redo,forecolor,bullist,link,unlink,image,media,cleanup,removeformat",
        theme_advanced_buttons2 : "formatselect,justifyleft,justifycenter,justifyright,justifyfull,code",
        theme_advanced_buttons3 : "",

        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align    : "left",

        theme_advanced_resizing : false,

        language           : "sk",
        relative_urls      : false,
        entity_encoding    : "raw",
        remove_script_host : false,
        convert_urls       : false,
        cleanup            : true

    });
</script>


<div class="newsletter">


    {*
    <div class="choose-template">
        <ul>
            <li>
                <div style="text-align:center;">
                    <img src="/images-system/newsletter/templates/template-1.png" alt=""/><br/>
                    <input type="radio" name="template[]" checked="checked"/>
                </div>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
    *}
    <h1>Newsletter</h1>


    <div class="newsletter-msg-holder">
        <div class="left">
            <h1>Správa na odoslanie</h1>
            <div style="padding: 10px 0;">
                {$form->render('begin')}
                {$form->render('errors')}
                <div class="subject-holder">
                    {$form['subject']->label|noescape}
                    {$form['subject']->control|noescape}
                </div>
                {$form['text']->control|noescape}

                <div class="c-text-email">
                    {$form['my_email']->label|noescape}
                    {$form['my_email']->control|noescape}
                    {$form['btn_send_to_me']->control|noescape}
                </div>


                <div class="send-input-holder">
                    {$form['btn_send_emails']->control|noescape}<br/>
                    <small>Newsletter sa odošle na všetky emaily, ktoré sú označené. Ak neoznačíte ani jeden email,
                        odošle sa newsletter na všetky emaily.
                    </small>
                </div>
                <div class="clear"></div>


                {$form->render('end')}
            </div>
        </div>
        <div class="right">
            <h3>Archív
                <small>( všetky odoslané správy )</small>
            </h3>
            <div class="archiv">
                {foreach $sended_msg as $s}
                <a href="{plink loadMessage $s->id_newsletter_sended_msg}"><span>{$s->date}</span>{$s->subject}</a>
                {/foreach}
            </div>

        </div>
        <div class="clear"></div>
    </div>


    <div class="newsletter-msg-holder">
        <div class="left">
            {snippet checkedEmails}
            <div class="checked-email-holder">

                <strong>Označené ({php echo count($checked_emails)}) </strong><br/>
                {foreach $checked_emails as $e} {$e['email']}{if !$iterator->isLast()},{/if}{/foreach}

            </div>
            {/snippet}


            <h1>Správa na odoslanie</h1>

            <div class="action">

                <a id="checkAllEmailsBtn" href="#">OZNAČ emaily na strane</a>
                <a id="uncheckAllEmailsBtn" href="#">ODZNAČ emaily na strane</a>
                <a id="uncheckAllEmailsSaved" href="#">ODZNAČ všetky</a>

                <a class="ajax confirm" href="{link deleteAllEmail!}">Zmazať všetky emaily</a>
            </div>

            {control newsletterTabella}

            <script>
                $('.checked_emails').live('click', function() {

                    if ($(this).is(':checked')) {
                        $.get({link checkedEmail
                        !1
                    }
                        +'&id_newsletter_emails[]=' + $(this).val()
                    )
                        ;
                    } else {
                        $.get({link checkedEmail
                        !0
                    }
                        +'&id_newsletter_emails[]=' + $(this).val()
                    )
                        ;
                    }
                });

                $('#checkAllEmailsBtn').click(function(e) {
                    e.preventDefault();
                    var emails_str = '';
                    $('.checked_emails').each(function() {
                        $(this).attr('checked', true);
                        emails_str += '&id_newsletter_emails[]=' + $(this).val();
                    });

                    $.get({link checkedEmail
                    !1
                }
                    +emails_str
                    )
                    ;
                });

                $('#uncheckAllEmailsBtn').click(function(e) {
                    e.preventDefault();

                    var emails_str = '';

                    $('.checked_emails').each(function() {
                        $(this).attr('checked', false);
                        emails_str += '&id_newsletter_emails[]=' + $(this).val();
                    });

                    $.get({link checkedEmail
                    !0
                }
                    +emails_str
                    )
                    ;
                });

                $('#uncheckAllEmailsSaved').click(function(e) {
                    e.preventDefault();
                    $.get({link uncheckedAllEmail
                    !
                })
                    ;
                });


            </script>
        </div>


        <div class="right">
            <h3>Pridanie emailov
                <small>( pre vloženie viacej emailových adresie odelte emaily čiarkou)</small>
            </h3>
            {$addform->render('begin')}
            {$addform['emails']->label|noescape}
            {$addform['emails']->control|noescape}

            {$addform['btn']->control|noescape}
            {$addform->render('end')}
        </div>
        <div class="clear"></div>
    </div>

    <script>
        $(document).ready(function() {
            $(".confirm").easyconfirm({locale : {title : 'Upozornenie', button : ['No', 'Yes']}});
        });
    </script>

</div>